# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_addparentchild'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paperback',
            field=models.CharField(blank=True, choices=[('S', 'Soft cover'), ('H', 'Hard cover')], default='', max_length=1, null=True),
        ),
    ]
