# Generated by Django 5.0.2 on 2024-02-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_bookwithchapternumbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="binary_field",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
